name: ev-motion
type: environment
description: Environment for e-motion D4G
dependencies:
- python =3.9.16
- anaconda::ipykernel

- conda-forge::pandas =1.4.2
- conda-forge::geopandas =0.13.1
- conda-forge::dask-geopandas =0.3.1

- conda-forge::folium =0.14.0
- conda-forge::scikit-learn =1.2.2
- conda-forge::scikit-learn-intelex
#- conda-forge::umap-learn=0.5.3
- conda-forge::numpy =1.25.0
- conda-forge::pyarrow =12.0.0
- conda-forge::seaborn #=0.12.2
- conda-forge::ipywidgets =8.0.6
- anaconda::ipython_genutils =0.2.0
# - conda-forge::css-html-js-minify
- conda-forge::shapely =2.0.1
- conda-forge::polyline =2.0.0
- conda-forge::iprogress =0.4

# - conda-forge::mapbox=0.18.1
# - conda-forge::pyrosm
- conda-forge::networkx =3.1
- conda-forge::osmnx =1.3.0
- conda-forge::tqdm =4.65.0
- conda-forge::pyproj #=3.5.0
# - conda-forge::geopy #=2.3.0